include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - avoid_print
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.config.dart
    - lib/**.freezed.dart